/**
 * Tailwind Resolver
 * 
 * Provides utilities to reverse-lookup computed CSS values to Tailwind classes.
 * Uses the resolved Tailwind config generated by the componentTagger plugin.
 */

// Types for resolved Tailwind config
interface TailwindConfig {
  theme: {
    colors: Record<string, string | Record<string, string>>;
    spacing: Record<string, string>;
    fontSize: Record<string, string | [string, { lineHeight?: string; letterSpacing?: string }]>;
    fontWeight: Record<string, string>;
    fontFamily: Record<string, string[]>;
    borderRadius: Record<string, string>;
    boxShadow: Record<string, string>;
    opacity: Record<string, string>;
    lineHeight: Record<string, string>;
    letterSpacing: Record<string, string>;
    // Add more as needed
  };
}

interface ResolvedTailwindClass {
  className: string;
  property: string;
  value: string;
  confidence: 'exact' | 'approximate';
}

interface DetectedClasses {
  fontSize?: ResolvedTailwindClass;
  fontWeight?: ResolvedTailwindClass;
  textColor?: ResolvedTailwindClass;
  backgroundColor?: ResolvedTailwindClass;
  borderColor?: ResolvedTailwindClass;
  borderRadius?: ResolvedTailwindClass;
  padding?: ResolvedTailwindClass;
  margin?: ResolvedTailwindClass;
  display?: ResolvedTailwindClass;
  opacity?: ResolvedTailwindClass;
  boxShadow?: ResolvedTailwindClass;
  // Add more as needed
}

// Singleton instance
let configInstance: TailwindConfig | null = null;
let reverseLookupMaps: {
  colors: Map<string, string>;
  spacing: Map<string, string>;
  fontSize: Map<string, string>;
  fontWeight: Map<string, string>;
  borderRadius: Map<string, string>;
  opacity: Map<string, string>;
} | null = null;

const DEBUG = false;

function log(message: string, data?: unknown) {
  if (!DEBUG) return;
  if (data !== undefined) {
    console.log(`[TailwindResolver] ${message}`, data);
  } else {
    console.log(`[TailwindResolver] ${message}`);
  }
}

/**
 * Load the resolved Tailwind config
 * Uses fetch to load the JSON file generated by componentTagger plugin.
 * The file is generated at src/tailwind.config.sa.json on Vite build start.
 */
export async function loadTailwindConfig(): Promise<TailwindConfig | null> {
  if (configInstance) {
    return configInstance;
  }

  try {
    // Fetch the config file from Vite dev server
    // The plugin generates it at src/tailwind.config.sa.json
    const response = await fetch('/src/tailwind.config.sa.json');
    if (!response.ok) {
      // File might not exist yet if plugin hasn't run - this is expected on first load
      if (response.status === 404) {
        log('Tailwind config not found (plugin may not have generated it yet)');
      } else {
        log(`Failed to load config: ${response.status} ${response.statusText}`);
      }
      return null;
    }
    
    configInstance = await response.json();
    log('Tailwind config loaded successfully');
    
    // Build reverse lookup maps
    buildReverseLookupMaps();
    
    return configInstance;
  } catch (error) {
    log('Error loading Tailwind config:', error);
    return null;
  }
}

/**
 * Build reverse lookup maps from config
 * Maps CSS values → Tailwind class names
 */
function buildReverseLookupMaps() {
  if (!configInstance) return;
  
  const { theme } = configInstance;
  
  reverseLookupMaps = {
    colors: new Map(),
    spacing: new Map(),
    fontSize: new Map(),
    fontWeight: new Map(),
    borderRadius: new Map(),
    opacity: new Map(),
  };

  // Build colors map (flatten nested color objects)
  if (theme.colors) {
    const flattenColors = (colors: Record<string, string | Record<string, string>>, prefix = '') => {
      for (const [key, value] of Object.entries(colors)) {
        if (typeof value === 'string') {
          const className = prefix ? `${prefix}-${key}` : key;
          const normalizedValue = normalizeColor(value);
          reverseLookupMaps!.colors.set(normalizedValue, className);
        } else if (typeof value === 'object') {
          flattenColors(value, key);
        }
      }
    };
    flattenColors(theme.colors);
  }

  // Build spacing map
  if (theme.spacing) {
    for (const [key, value] of Object.entries(theme.spacing)) {
      reverseLookupMaps.spacing.set(value, key);
    }
  }

  // Build fontSize map
  if (theme.fontSize) {
    for (const [key, value] of Object.entries(theme.fontSize)) {
      const size = Array.isArray(value) ? value[0] : value;
      reverseLookupMaps.fontSize.set(size, `text-${key}`);
    }
  }

  // Build fontWeight map
  if (theme.fontWeight) {
    for (const [key, value] of Object.entries(theme.fontWeight)) {
      reverseLookupMaps.fontWeight.set(value, `font-${key}`);
    }
  }

  // Build borderRadius map
  if (theme.borderRadius) {
    for (const [key, value] of Object.entries(theme.borderRadius)) {
      const className = key === 'DEFAULT' ? 'rounded' : `rounded-${key}`;
      reverseLookupMaps.borderRadius.set(value, className);
    }
  }

  // Build opacity map
  if (theme.opacity) {
    for (const [key, value] of Object.entries(theme.opacity)) {
      reverseLookupMaps.opacity.set(value, `opacity-${key}`);
    }
  }

  log('Reverse lookup maps built', {
    colors: reverseLookupMaps.colors.size,
    spacing: reverseLookupMaps.spacing.size,
    fontSize: reverseLookupMaps.fontSize.size,
    fontWeight: reverseLookupMaps.fontWeight.size,
    borderRadius: reverseLookupMaps.borderRadius.size,
    opacity: reverseLookupMaps.opacity.size,
  });
}

/**
 * Normalize color values to a consistent format for comparison
 */
function normalizeColor(color: string): string {
  // Handle CSS variables - can't normalize these
  if (color.includes('var(')) {
    return color;
  }
  
  // Convert hex to lowercase
  if (color.startsWith('#')) {
    return color.toLowerCase();
  }
  
  // Normalize rgb/rgba
  const rgbMatch = color.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/);
  if (rgbMatch) {
    const [, r, g, b, a] = rgbMatch;
    if (a !== undefined && parseFloat(a) < 1) {
      return `rgba(${r}, ${g}, ${b}, ${a})`;
    }
    return rgbToHex(parseInt(r), parseInt(g), parseInt(b));
  }
  
  return color;
}

/**
 * Convert RGB to hex
 */
function rgbToHex(r: number, g: number, b: number): string {
  return '#' + [r, g, b].map(x => {
    const hex = x.toString(16);
    return hex.length === 1 ? '0' + hex : hex;
  }).join('');
}

/**
 * Detect Tailwind classes from computed styles
 */
export function detectTailwindClasses(computedStyles: CSSStyleDeclaration): DetectedClasses {
  const detected: DetectedClasses = {};
  
  if (!reverseLookupMaps) {
    log('Reverse lookup maps not initialized');
    return detected;
  }

  // Detect font size
  const fontSize = computedStyles.fontSize;
  if (fontSize) {
    const match = reverseLookupMaps.fontSize.get(fontSize);
    if (match) {
      detected.fontSize = {
        className: match,
        property: 'fontSize',
        value: fontSize,
        confidence: 'exact',
      };
    }
  }

  // Detect font weight
  const fontWeight = computedStyles.fontWeight;
  if (fontWeight) {
    const match = reverseLookupMaps.fontWeight.get(fontWeight);
    if (match) {
      detected.fontWeight = {
        className: match,
        property: 'fontWeight',
        value: fontWeight,
        confidence: 'exact',
      };
    }
  }

  // Detect text color
  const color = normalizeColor(computedStyles.color);
  const textColorMatch = reverseLookupMaps.colors.get(color);
  if (textColorMatch) {
    detected.textColor = {
      className: `text-${textColorMatch}`,
      property: 'color',
      value: color,
      confidence: 'exact',
    };
  }

  // Detect background color
  const bgColor = normalizeColor(computedStyles.backgroundColor);
  if (bgColor !== 'rgba(0, 0, 0, 0)' && bgColor !== 'transparent') {
    const bgMatch = reverseLookupMaps.colors.get(bgColor);
    if (bgMatch) {
      detected.backgroundColor = {
        className: `bg-${bgMatch}`,
        property: 'backgroundColor',
        value: bgColor,
        confidence: 'exact',
      };
    }
  }

  // Detect border radius
  const borderRadius = computedStyles.borderRadius;
  if (borderRadius && borderRadius !== '0px') {
    const radiusMatch = reverseLookupMaps.borderRadius.get(borderRadius);
    if (radiusMatch) {
      detected.borderRadius = {
        className: radiusMatch,
        property: 'borderRadius',
        value: borderRadius,
        confidence: 'exact',
      };
    }
  }

  // Detect opacity
  const opacity = computedStyles.opacity;
  if (opacity && opacity !== '1') {
    const opacityMatch = reverseLookupMaps.opacity.get(opacity);
    if (opacityMatch) {
      detected.opacity = {
        className: opacityMatch,
        property: 'opacity',
        value: opacity,
        confidence: 'exact',
      };
    }
  }

  // Detect display
  const display = computedStyles.display;
  if (display) {
    const displayClasses: Record<string, string> = {
      'block': 'block',
      'inline-block': 'inline-block',
      'inline': 'inline',
      'flex': 'flex',
      'inline-flex': 'inline-flex',
      'grid': 'grid',
      'inline-grid': 'inline-grid',
      'none': 'hidden',
    };
    if (displayClasses[display]) {
      detected.display = {
        className: displayClasses[display],
        property: 'display',
        value: display,
        confidence: 'exact',
      };
    }
  }

  return detected;
}

/**
 * Get available color options from config
 */
export function getAvailableColors(): Array<{ name: string; value: string; cssValue: string }> {
  if (!configInstance?.theme.colors) return [];
  
  const colors: Array<{ name: string; value: string; cssValue: string }> = [];
  
  const extractColors = (obj: Record<string, string | Record<string, string>>, prefix = '') => {
    for (const [key, value] of Object.entries(obj)) {
      if (typeof value === 'string') {
        const name = prefix ? `${prefix}-${key}` : key;
        colors.push({ name, value: name, cssValue: value });
      } else if (typeof value === 'object') {
        extractColors(value, key);
      }
    }
  };
  
  extractColors(configInstance.theme.colors);
  return colors;
}

/**
 * Get available spacing options from config
 */
export function getAvailableSpacing(): Array<{ name: string; value: string }> {
  if (!configInstance?.theme.spacing) return [];
  
  return Object.entries(configInstance.theme.spacing).map(([name, value]) => ({
    name,
    value,
  }));
}

/**
 * Get available font sizes from config
 */
export function getAvailableFontSizes(): Array<{ name: string; value: string; className: string }> {
  if (!configInstance?.theme.fontSize) return [];
  
  return Object.entries(configInstance.theme.fontSize).map(([name, value]) => ({
    name,
    value: Array.isArray(value) ? value[0] : value,
    className: `text-${name}`,
  }));
}

/**
 * Get available font weights from config
 */
export function getAvailableFontWeights(): Array<{ name: string; value: string; className: string }> {
  if (!configInstance?.theme.fontWeight) return [];
  
  return Object.entries(configInstance.theme.fontWeight).map(([name, value]) => ({
    name,
    value,
    className: `font-${name}`,
  }));
}

/**
 * Get available border radius options from config
 */
export function getAvailableBorderRadius(): Array<{ name: string; value: string; className: string }> {
  if (!configInstance?.theme.borderRadius) return [];
  
  return Object.entries(configInstance.theme.borderRadius).map(([name, value]) => ({
    name,
    value,
    className: name === 'DEFAULT' ? 'rounded' : `rounded-${name}`,
  }));
}

/**
 * Get the full resolved config (for advanced use)
 */
export function getResolvedConfig(): TailwindConfig | null {
  return configInstance;
}

export type { TailwindConfig, DetectedClasses, ResolvedTailwindClass };

